package uz.gfu.gfu_atvxkb_tg_bot.enums;

public enum UserState {
    START,
    CHOOSE_LANG,
    SHARE_PHONE_NUMBER,
    GET_BUILDING,
    GET_DEPARTMENT,
    GET_SUB_FEEDBACK,
    LAST_NAME,
    NAME,
    BLOCK,
    GET_ROOM_NUM,
    REGISTER_DONE,
    GET_FEEDBACK,
    SUCCESS,
    SAVE_SUB_FEEDBACK,
    SETTING,
    SUPER_ADMIN_CRUD,
    SUPER_ADMIN_BUILDING,
    ADD_BUILDING_STATE,
    ADMIN_FOR_FEEDBACK,
    EDIT_BUILDING_STATE
}
